# Generated by Django 2.2.3 on 2019-08-04 09:59

import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields
import usercenter.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='部门名称', max_length=50, verbose_name='名称')),
                ('category', models.CharField(choices=[('厅', '厅'), ('厅机关', '厅机关'), ('事业单位', '事业单位')], default='厅机关', max_length=15, verbose_name='部门类别')),
                ('contact_name', models.CharField(blank=True, help_text='联系人', max_length=16, null=True, verbose_name='联系人')),
                ('contact_phone', models.CharField(blank=True, help_text='联系电话', max_length=32, null=True, verbose_name='联系电话')),
                ('contact_mobile', models.CharField(blank=True, help_text='手机号', max_length=32, null=True, verbose_name='手机号')),
                ('contact_fax', models.CharField(blank=True, help_text='传真', max_length=32, null=True, verbose_name='传真')),
                ('description', models.TextField(blank=True, help_text='说明', null=True, verbose_name='说明')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, help_text='上级部门', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='usercenter.Department', verbose_name='上级部门')),
            ],
            options={
                'verbose_name': '机构部门',
                'verbose_name_plural': '机构部门',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': '用户名已存在。'}, help_text='必填，小于150个字符。', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='用户名')),
                ('full_name', models.CharField(blank=True, help_text='姓名', max_length=30, verbose_name='姓名')),
                ('email', models.EmailField(blank=True, help_text='Email', max_length=254, null=True, verbose_name='Email')),
                ('mobile', models.CharField(blank=True, help_text='手机号码', max_length=32, null=True, verbose_name='手机号码')),
                ('phone', models.CharField(blank=True, help_text='办公电话', max_length=32, null=True, verbose_name='办公电话')),
                ('is_staff', models.BooleanField(default=False, help_text='可进入后台管理', verbose_name='可进入后台管理')),
                ('is_active', models.BooleanField(default=True, help_text='允许登录', verbose_name='允许登录')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('inner_code', models.CharField(blank=True, help_text='内部工号', max_length=32, null=True, verbose_name='内部工号')),
                ('employee_position', models.CharField(blank=True, help_text='职务', max_length=32, null=True, verbose_name='职务')),
                ('employee_rank', models.CharField(blank=True, choices=[('领导班子', '领导班子'), ('中层干部', '中层干部'), ('普通', '普通')], max_length=32, null=True, verbose_name='职别')),
                ('description', models.TextField(blank=True, help_text='备注', null=True, verbose_name='备注')),
                ('department', models.ForeignKey(blank=True, help_text='部门', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='usercenter.Department', verbose_name='部门')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['-pk'],
            },
            managers=[
                ('objects', usercenter.models.UserManager()),
            ],
        ),
    ]
